### ISSUE TITLE
Darkend branding carried over by accident

### ISSUE THREAD

**Issue by didlly** [Sxvxgee/LightNuke#1]
Darkend branding was accidentally copied over to `lightnuke()` in `/utils/misc.py`. Exact link is [here](https://github.com/Sxvxgee/LightNuke/blob/main/utils/misc.py#L15).

```python
def lightnuke(text):
  text = str(text).replace('\n', '\n[Darkend] ')
  print(f"[bold cyan][Darkend] {text}[/bold cyan]")
```

![image](https://user-images.githubusercontent.com/94558954/171865650-fe1bbeef-d18e-4078-a977-38226c3a11c1.png)

PS: Currently there is no need to import `threading` in the same file, but this is the first commit so ig maybe soon that will be changed ;-).

**Comment by Sxvxgee** [comment]
`Threading` was imported for something I was testing but I forgot to remove the import since the test was a failure.

Also thanks for reminding me of that typo, I forgot to change it, lol.

**Comment by Sxvxgee** [comment]
Fixed.
